# Generated by Django 2.0.6 on 2019-06-15 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='Translation',
            new_name='translation',
        ),
        migrations.AddField(
            model_name='customer',
            name='agreement_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
